### ISSUE TITLE
error：

### ISSUE THREAD

**Issue by qianbudiao6** [abhijeet3922/Speaker-identification-using-GMMs#6]
it has such a problem now：cPickle.dump(gmm,open(dest + picklefile,'w'))
IOError: [Errno 2] No such file or directory: 'speaker_models\\anthonyschaller.gmm'，can yoy help me solve it? thanks

**Comment by shikharparikh** [comment]
Are you using Windows or Ubuntu?

**Comment by Jhenriquee** [comment]
As @shikharparikh asked, if you're using an unix based system as linux/OSX you'll need to replace the '\\' to '/' on the "development_set_test.txt" and "development_set_enroll.txt", also you'll need to change it on the .py files the variables "source" and "dest" too.

**Comment by qianbudiao6** [comment]
I have  solved it，thank you

**Comment by nikbohra** [comment]
when iam running the test.py file i am getting this can you help me to solve it

 return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 30: character maps to <undefined>

**Comment by shikharparikh** [comment]
@nikbohra please send the line of the script in which you're facing the error.

**Comment by nikbohra** [comment]
> @nikbohra please send the line of the script in which you're facing the error.

i have solved the error 

i have replace this line -- models    = [cPickle.load(open(fname,'r')) for fname in gmm_files]

by -- models    = [cPickle.load(open(fname,'rb')) for fname in gmm_files]

**Comment by nikbohra** [comment]
now as i am trying to make my own dataset and when i am giving the path to train models it is showing

fid = open(filename, 'rb')

PermissionError: [Errno 13] Permission denied: 'C:/Users/bohra/Desktop/Speaker-identification-using-GMMs-master/training_data/'

**Comment by nikbohra** [comment]
@shikharparikh 

now as i am trying to make my own dataset and when i am giving the path to train models it is showing
fid = open(filename, 'rb')
PermissionError: [Errno 13] Permission denied: 'C:/Users/bohra/Desktop/Speaker-identification-using-GMMs-master/training_data/

**Comment by shikharparikh** [comment]
Try running the program as administrator

**Comment by nikbohra** [comment]
@shikharparikh 
below shown is the issue that is been seen on the console while running as administrator

Traceback (most recent call last):

  File "<ipython-input-32-a24d35cabf49>", line 1, in <module>
    runfile('C:/Users/bohra/Desktop/Speaker-identification-using-GMMs-master/train_models.py', wdir='C:/Users/bohra/Desktop/Speaker-identification-using-GMMs-master')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/bohra/Desktop/Speaker-identification-using-GMMs-master/train_models.py", line 33, in <module>
    sr,audio = read(source + path)

  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\wavfile.py", line 233, in read
    fid = open(filename, 'rb')

PermissionError: [Errno 13] Permission denied: 'C:/Users/bohra/Desktop/Speaker-identification-using-GMMs-master/training_data/'

**Comment by alonyomtov123** [comment]
> > @nikbohra please send the line of the script in which you're facing the error.
> 
> i have solved the error
> 
> i have replace this line -- models = [cPickle.load(open(fname,'r')) for fname in gmm_files]
> 
> by -- models = [cPickle.load(open(fname,'rb')) for fname in gmm_files]

I had the same issue. this didnt solve it.
Can anyone help?

**Comment by Bishree** [comment]
> I have solved it，thank you

Hello, dear, I have the same issue can you plz tell me how did solve it? any help will be highly appreciated.
I'm using Ubuntu 20.04 
python 3.8

**Comment by FeatureShabeer** [comment]
I'm facing this issue in my voice authentication code while running the scikit-learn latest version, any one please guide me how did i solve this, Thank you in advance
Error : " ModuleNotFoundError: No module named 'sklearn.mixture.gmm' "




Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\AliSa\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\AliSa\Speaker-Recognition-master\test.py", line 62, in testaudio
    k = test1()
  File "C:\Users\AliSa\Speaker-Recognition-master\username.py", line 68, in test1
    models    = [pickle.load(open(fname,'rb')) for fname in gmm_files]
  File "C:\Users\AliSa\Speaker-Recognition-master\username.py", line 68, in <listcomp>
    models    = [pickle.load(open(fname,'rb')) for fname in gmm_files]
ModuleNotFoundError: No module named 'sklearn.mixture.gmm'
